### PR TITLE
Update cvss3.py

### LINKED ISSUE #34: Temporal and environmental severities reversed in json output
Hi,
I've discovered a problem while using an environmental severity with the cvss3 implementation:
When using the as_json() function in the latest version the temporal and environmental severities are switched.

See: https://github.com/skontar/cvss/blob/5f8e1e8f3ba557fa44d83a4e1c488f466e9b7286/cvss/cvss3.py#L474-L475

### PR DESCRIPTION
**Pull request by Roang-zero1**
Fix reversed temporal and environmental severity in as_json() for cvss3

Fixes #34

### CODE REVIEW

**Comment by skontar** [comment]
Thank for your contribution! Can you please also fix the typo in "environmental_everity"? Thank you!

**Comment by Roang-zero1** [comment]
Didn't even notice that; fixed.

**Comment by Roang-zero1** [comment]
Before you merge this let me add a new test scenario to prevent a regression at a later date.

I'll look into it tomorrow.

**Comment by Roang-zero1** [comment]
Now that it's the correct commit the test is working.
Should be good to go from my side

**Comment by skontar** [comment]
@Roang-zero1 Thanks for your contribution. Do you also need a pypi release?

**Comment by Roang-zero1** [comment]
@skontar Is cloud you please check the release workflow, I see the commit but neither a tag nor a new release on pypi.
Thanks!

**Comment by skontar** [comment]
@Roang-zero1 thanks for letting me know. Please check now.

**Comment by Roang-zero1** [comment]
Thanks for checking, it's up now.

**Pull request merged**
