### PR TITLE
Generate CVSS v2 severities

### PR DESCRIPTION
**Pull request by AetherDeity**
Add function to generate severities for CVSS v2 based on https://nvd.nist.gov/vuln-metrics/cvss in same way as CVSS v3

### CODE REVIEW

**Comment by skontar** [comment]
I completely forgot about this. I will try to find some time and merge it next week. Sorry about that.

**Comment by skontar** [comment]
The code looks good, however tests fail. Please double-check.

**Comment by AetherDeity** [comment]
@skontar sorry I wasnt able to get back to this sooner. Thought I had run tests locally, but it would seem not. Tests should be fixed

**Comment by skontar** [comment]
Thank you for contributing. I am planning to do a release next week.

**Pull request merged**
